### ISSUE TITLE
Physical keyboard backlight does not work

### ISSUE THREAD

**Issue by lazycodeninja** [tdm/android_device_fxtec_pro1#10]
When opening the keyboard, the keys aren't backlit.  I don't see any option to enable/control this in the input settings.

**Comment by Eevoo** [comment]
I'm not having the same problem. My device auto-activates the backlight when opened, then turns it off after a period of about 20 seconds of inactivity. 5 seconds or so if on the lock screen. 

I tested to see if the ambient light sensor was turning the backlight off due to higher ambient light, then forgetting to turn it back on when the ambient light went away, but as best I can tell, while the screen brightness went up and down, the backlight stayed lit. 

![image](https://user-images.githubusercontent.com/49214133/71557113-a3405600-2a0f-11ea-8604-8c895756e9b4.png)

**Comment by CommanderStrax** [comment]
Still an issue with version 3.

**Comment by JooJooBee666** [comment]
Indeed, this is a known issue as Lineage doesn't have a native way to control the keyboard backlight.  Work is being done to address this but you can use this app I made called [KB Backlight Manager.](https://community.fxtec.com/topic/2721-kb-backlight-manager-for-lineageos-builds/) to restore functionality.

**Comment by tdm** [comment]
Fixed by importing @mccreary's lights HAL changes.
