### ISSUE TITLE
Keyboard layout QWERTZ not correct

### ISSUE THREAD

**Issue by ghost** [tdm/android_device_fxtec_pro1#35]
So, I have lost track of what is going on with the keyboard layout in the forum thread. This is the current state on test8:

- Selecting the correct region (German) in the physical keyboard setting, nothing happens.
- Going into System/Keyboard and setting QWERTZ there enables basic input that works.

Incorrect things here:
  - The <> key produces ^ and °
  - Sym + Q produces @, which I guess means that Sym == Alt Gr on a normal keyboard. However, Sym +U/I/O/P/Ü/Ö/Ö/Ä does not produce any output.  Curiously, Sym+M produces the correct output again -> µ

Question:
 - Would it be possible/feasible to make Sym sticky if pressed once instead of popping open the virtual keyboard?

**Comment by rehejuhan** [comment]
Thanks for opening the issue with German qwertz layout. In addition to abovementioned problems:
1. I guess the "yellow arrow pointing to North-East" (Fn key?)is meant to get the yellow characters on the keyboard keys. Currently it just seems to double the Shift key.
2. This gives mostly correct results only for the upper road. (If wanted to be very precise, then the Shift key should not do anything there and Fn key giving "yellow characters").
3. In case of letters, the Fn + letter key gives just capital letter not the yellow characters (as does the Shift+letter key).
4. For non-letter keys (+ , . -) Fn doubles the Shift key
5. What sould do the Strg, FxTec, Alt and Sym keys? Sym key in some cases (as stated the first post) works as a Fn key (@ and µ), however Sym+* gives ~.

**Comment by Gigadoc2** [comment]
I suspect this is in part the consequence of how the rewritten keyboard driver is intended to work for the qwertY layout. AFAIK, the qwertY keyboard on the pro1 is almost the entire alphanumeric section of an ANSI keyboard + arrow keys. In other words, there are no "symbol keys" (as opposed to control keys like Home) missing, so you can input almost every key with just Shift as a modifier.
In fact, the only key that I see missing is the "/ ?" key which has been replaced by Delete. Given that, it seems to me like the only two symbols you need to use a third modifier for are '/' and '?' (which makes me wonder a bit why F(x)tec went with the design of Fn keys at all, with two of them no less, but maybe someone who has watched the design process more closely knows more about that).
So, tdm has decided to make the keyboard appear as a full PC keyboard to Android, using Fn key mappings in the kernel driver to make up for the missing symbol key (and then some control keys, because we can).

Now, the qwertZ layout the pro1 ships is mostly based on the german PC layout, but there is a problem: The german PC layout is based on an ISO keyboard, which has one key more. Where the ANSI keyboards have shift, the ISO keyboard has shift and another key. That key is the "< >" key, so I guess that is where some of the confusion comes from. In addition to that, while the US qwertY layout uses mostly two layers (I think, I might be wrong), regular level 1 and Shift for level 2, the german layout uses a _third_ level with a key we call "Alt Gr", which is the right Alt key on US qwertY. That third level is mostly unused (fun fact, there is even a fourth level, but I don't even know how to get to that), except for 8 symbols: "@", "{", "[", "]", "}", "\", "|" and "~". One could argue (I wouldn't) that those keys (except @) are not needed on a mobile, but F(x)tec has decided to include those.
Now what this all means is that the qwertZ layout as printed on the keyboard (and handled in stock) differs way more from a PC layout than the qwertY layout does, there are a lot more special keys that are only reachable via Fn.

Now, why am I writing all this background info? Fixing the driver built-in layout as to match the printed layout should be something I could do, but I am unsure how @tdm wants to handle this: AFAIS the driver is made to act like mostly like a PC keyboard would. For qwertY that means that only two keys behave specially with Fn, all others just work with shift like you would expect. So the layout as printed matches what the driver does. Now with the qwertZ layout, because of all the reasons above, the print does _not_ match a PC keyboard. The print mixes together keys from the third level with the two "missing" keys, and since it assumes both that no third level is being used _and_ that Fn can be used in place of Shift for the number row, most of the third-level keys have been moved around.
So, since the print is very different from the PC layout, I am unsure which way to go:
 * Make the keyboard act like the PC version, or
 * Make the keyboard act like the print

On stock there is no choice, since the "Sym" key does not act as a modifier (or do anything yet), but with tdms driver in LineageOS, the "Sym" key acts as "right Alt", which means "Alt Gr", AKA our level 3 modifier. So it would be possible to have the keyboard act mostly like a PC keyboard, by using Fn only for the two missing keys and "Sym" as "Alt Gr" does on a PC.

Personally, I am strongly in favor of the second option, to make the keyboard act like the print suggests. Not only because I sometimes need to look at the print to press the right key, but also because "Sym" is in a really awkward position for a modifier, while Fn is even better reachable than Shift (and there are two of it). But I realize that that would be dissonant with that the qwertY layout does, and I could understand if tdm does not want to go in that direction. And the situation is made even more complicated by the fact that "Sym" is a sticky modifier while "Fn" is not: People might prefer the first option simply for that.

The good thing is, with the drivers ability to customize layouts it will be easy for those who prefer whatever option does not end up being the default to change it with a single file. But still, the question is what _is_ to become the default.

> In case of letters, the Fn + letter key gives just capital letter not the yellow characters (as does the Shift+letter key).
Are you sure? It acts like Shift in the number row, but for the alphabetic key it does not for me. Keep in mind that the first letter you type is capitalized anyway by Android.

> Sym key in some cases (as stated the first post) works as a Fn key (@ € and µ), however Sym+* gives ~. Also Sym+2 and Sym+3 gives them as upper index. Longpressing Sym gives virtual keyboard symbols page which seems reasonable.

That is because "Sym" is what "Alt Gr" is on your PC keyboard, and thus "works as expected" even if it is not on the print. I assume that, whatever option is chosen for the driver keymap, this behaviour will stay as it is part of the userland keymap handling, and the driver-level keymap was introduced exactly to avoid having to change all the userland layouts (personally I would have preferred that, but I fully understand and accept why tdm has chosen not to).

> What should do the Strg, FxTec and Alt keys?
First, for the non-german speaking people: "Strg" is "Ctrl". Strg and Alt behave like they do on a PC, you can use them for shortcuts in Apps or Terminal Emulators (e.g. Firefox opens a new tab on Strg+T). Alt+Tab also does app-switching, but apart from that I don't know of any places in Android itself where those two keys are used.
The FxTec key is, in LineageOS, mapped as "Meta", which is roughly equivalent to the "Super" Key on a PC (that key that often has a Windows logo on it) or the "Search" key on Chromebooks. It can only be used for preconfigured shortcuts in Android, though there was some talk about making those editable somehow. Pressing it on it's own triggers the "Assistant App" (Possibly Google Assistant if you have GApps, but can also be handled by a different App, it's a setting). You can find all of the shortcuts by (on a qwertZ keyboard) pressing it + pressing "ß".

As there is some confusion about how the layout looks, with a lot of pictures on the Internet being pre-production devices with a different layout, here is a picture:
![pro1](https://user-images.githubusercontent.com/1494790/75705899-387ff500-5cb4-11ea-9fbd-be79012bfaff.jpg)
And a pc105 keyboard with qwertZ for reference:
![pc105](https://user-images.githubusercontent.com/1494790/75705982-5b120e00-5cb4-11ea-86c5-571e3cb8dc21.jpg)
Just, uuh, imagine "Num lock" where the any key is.

**Comment by rehejuhan** [comment]
Thanks for a thorough reply!
> > In case of letters, the Fn + letter key gives just capital letter not the yellow characters (as does the Shift+letter key).
> 
> Are you sure? It acts like Shift in the number row, but for the alphabetic key it does not for me. Keep in mind that the first letter you type is capitalized anyway by Android.
> 
Yes, I was only partially right - Fn+ü; Fn+ö and Fn+ä are giving capital letters.  For all other letter keys Fn key seems to do nothing.

**Comment by rehejuhan** [comment]
Yes, please - second option, to make the keyboard act like the print suggests.
[https://community.fxtec.com/topic/2509-lineageos-current-status-160-test-builds/page/22/?tab=comments#comment-45512](url)
So, according to the above link and some trial&error tests it was relatively easy to fix the following keys to get the Fn key act as printed:
11:0033:8033 (, and ;)
26:002c:0026 (y and |)
30:0011:0029 (w and ^)
38:0013:8029 (r and °)
39:0028:002b (ä and #)
47:0026:802b (l and ')
For other keys - still searching...

**Comment by Loader009** [comment]
Just as a reference, because I needed some time to find the post to apply qwertz via adb shell:
```
mkdir -p /persist/data/keyboard
echo "qwertz" > /persist/data/keyboard/layout 
```
https://community.fxtec.com/topic/2509-lineageos-current-status-160-test-builds/page/20/?tab=comments#comment-44863

PS: @rehejuhan your link is broken, please fix it. Thanks

**Comment by rehejuhan** [comment]
There is settings UI for keyboard and touchscreen since test 8 and it seems to work OK. Both settings should be set (german language and qwertz in respective settings).

> This is all very tedious, error prone, and time consuming.  So you can create a file "/persist/data/keyboard/keymap" that has the keymap that you like and it will be loaded at boot. 
This (after editing the key codes and copying result to /persist/data/keyboard/keymap) seems not to work, after a reboot the the default keymap was still loaded...

**Comment by rehejuhan** [comment]
So after a major progress described [here](https://community.fxtec.com/topic/2509-lineageos-current-status-160-test-builds/page/40/?tab=comments#comment-48720), there are left only two small glitches:
1. yellow-key plus l should give ' (apostrophe), at moment it gives ' (dead acute accent) but this is easily fixable with "47:0026:802b".
2. yellow-key pluss ü gives ~ (tilde) but for it to be really useful should give dead_tilde...

**Comment by rehejuhan** [comment]
Seems to be fixed in test16. At least all the keys correspond to what is printed on them.
The only small glitch left is Fn+ü result is ~ (tilde) but to get for example a letter õ it should be a dead_tilde...

**Comment by tdm** [comment]
This should be fixed per the forum discussion.
