### ISSUE TITLE
Virtual keyboard should default to enabled

### ISSUE THREAD

**Issue by tdm** [tdm/android_device_fxtec_pro1#5]
This is stock behavior.

**Comment by CommanderStrax** [comment]
Still an issue. Virtual keyboard won't pop up. Even after the initialization screen.

**Comment by EvilDragon** [comment]
The problem is not, that it this setting should be enabled.
The problem is, that the physical keyboard should only be active when you slide it out.
When that is fixed, the virtual keyboard will properly show.

I've opened this as it's own issue here: https://github.com/tdm/android_device_fxtec_pro1/issues/19

**Comment by tdm** [comment]
Should be fixed now.
